/* eslint-disable max-len */
const presets = {
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed Ft Flexi and Aderrasi [feat moebius transformation] - him beam": require(`./json/ssmcurtis/2013/Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Ludicrous speed Ft Flexi and Aderrasi [feat moebius transformation] - him beam.json`),
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash ": require(`./json/ssmcurtis/2013/Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash .json`),
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash _1": require(`./json/ssmcurtis/2013/Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash _1.json`),
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi_1": require(`./json/ssmcurtis/2013/Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi_1.json`),
  "AdamFX Mashup 2 Martin - reflections on black tile + Flexi + Raron n Orb  = Phat ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tile + Flexi + Raron n Orb  = Phat .json`),
  "AdamFX Mashup 2 Martin - reflections on black tile + Flexi + Raron n Orb ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tile + Flexi + Raron n Orb .json`),
  "AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tile + Raron N Flexi .json`),
  "AdamFX Mashup 2 Martin - reflections on black tile + Shiney Tunnel ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tile + Shiney Tunnel .json`),
  "AdamFX Mashup 2 Martin - reflections on black tile + StarFeild Sectors ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tile + StarFeild Sectors .json`),
  "AdamFX Mashup 2 Martin - reflections on black tiles + starfeild Sectors ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tiles + starfeild Sectors .json`),
  "AdamFX Mashup 2 Martin - reflections on black tiles + Wire Dance ": require(`./json/ssmcurtis/2013/AdamFX Mashup 2 Martin - reflections on black tiles + Wire Dance .json`),
  "bdrv + al Rovastar - A Million Miles from Earth mxvi": require(`./json/ssmcurtis/2013/bdrv + al Rovastar - A Million Miles from Earth mxvi.json`),
  "bdrv + al Rovastar - Dark Ritual (star Of Destiny Mix) rmx": require(`./json/ssmcurtis/2013/bdrv + al Rovastar - Dark Ritual (star Of Destiny Mix) rmx.json`),
  "bdrv + al Rovastar - Explosive Minds Bug Mix  rmx2 - my mind is hell": require(`./json/ssmcurtis/2013/bdrv + al Rovastar - Explosive Minds Bug Mix  rmx2 - my mind is hell.json`),
  "bdrv + al Rovastar - Fractopia bdrv132456 mix bleuarg - maple nostrum": require(`./json/ssmcurtis/2013/bdrv + al Rovastar - Fractopia bdrv132456 mix bleuarg - maple nostrum.json`),
  "cope - specimen 184": require(`./json/ssmcurtis/2013/cope - specimen 184.json`),
  "cope - strange attractor [flexis let it grow mix] (janky ripple effects)": require(`./json/ssmcurtis/2013/cope - strange attractor [flexis let it grow mix] (janky ripple effects).json`),
  "Flexi, Rovastar + Geiss - Fractopia vs bas relief": require(`./json/ssmcurtis/2013/Flexi, Rovastar + Geiss - Fractopia vs bas relief.json`),
  "3Dragons&idiot-beatfallspremix": require(`./json/ssmcurtis/2014/3Dragons&idiot-beatfallspremix.json`),
  "fanciful bratwurst engine": require(`./json/ssmcurtis/2014/fanciful bratwurst engine.json`),
  "martin - soma in pink": require(`./json/ssmcurtis/2014/martin - soma in pink.json`),
  "ultraremix 308": require(`./json/ssmcurtis/2014/ultraremix 308.json`),
  "ultraremix 44": require(`./json/ssmcurtis/2014/ultraremix 44.json`),
  "unable to find meaning matterspace swap nz": require(`./json/ssmcurtis/2014/unable to find meaning matterspace swap nz.json`),
  "unburythat f": require(`./json/ssmcurtis/2014/unburythat f.json`),
  "_geiss - 3 layers g2": require(`./json/ssmcurtis/2014/_geiss - 3 layers g2.json`),
  "_Geiss - Dancing Spirits": require(`./json/ssmcurtis/2014/_Geiss - Dancing Spirits.json`),
  "cope - digital sea": require(`./json/ssmcurtis/2016/cope - digital sea.json`),
  "Eo.S. + Geiss - glowsticks v2 02 (Relief Mix)": require(`./json/ssmcurtis/2016/Eo.S. + Geiss - glowsticks v2 02 (Relief Mix).json`),
  "Eo.S. + Geiss - glowsticks v2 03 music shifter edit b (water mix)": require(`./json/ssmcurtis/2016/Eo.S. + Geiss - glowsticks v2 03 music shifter edit b (water mix).json`),
  "Eo.S. + Geiss - sarc c_Phats Zoom Mix Reflecto": require(`./json/ssmcurtis/2016/Eo.S. + Geiss - sarc c_Phats Zoom Mix Reflecto.json`),
  "Eo.S. + Phat - chasers 11 sentinel C_poltergeist_mix response daemon": require(`./json/ssmcurtis/2016/Eo.S. + Phat - chasers 11 sentinel C_poltergeist_mix response daemon.json`),
  "fed - slowfast 1.1": require(`./json/ssmcurtis/2016/fed - slowfast 1.1.json`),
  "Flexi + Geiss - Bipolar vs. Reaction Diffusion mix": require(`./json/ssmcurtis/2016/Flexi + Geiss - Bipolar vs. Reaction Diffusion mix.json`),
  "Flexi + Geiss - pogo-cubes on tokamak matter [mind over matter remix]": require(`./json/ssmcurtis/2016/Flexi + Geiss - pogo-cubes on tokamak matter [mind over matter remix].json`),
  "Flexi + Geiss - pogo-cubes on tokamak matter": require(`./json/ssmcurtis/2016/Flexi + Geiss - pogo-cubes on tokamak matter.json`),
  "Flexi - cell tissue": require(`./json/ssmcurtis/2016/Flexi - cell tissue.json`),
  "flexi - color strike": require(`./json/ssmcurtis/2016/flexi - color strike.json`),
  "Flexi - mindblob [shiny mix]": require(`./json/ssmcurtis/2016/Flexi - mindblob [shiny mix].json`),
  "Flexi - psychenapping": require(`./json/ssmcurtis/2016/Flexi - psychenapping.json`),
  "Flexi - supersonic": require(`./json/ssmcurtis/2016/Flexi - supersonic.json`),
  "Flexi - the distant point between": require(`./json/ssmcurtis/2016/Flexi - the distant point between.json`),
  "Flexi, fishbrain, Geiss + Martin - tokamak witchery": require(`./json/ssmcurtis/2016/Flexi, fishbrain, Geiss + Martin - tokamak witchery.json`),
  "Flexi, Stahlregen, Nitorami + Shifter - shader authoring motivation set": require(`./json/ssmcurtis/2016/Flexi, Stahlregen, Nitorami + Shifter - shader authoring motivation set.json`),
  "Geiss - Liquid Beats (janky ripple warp reflecto)": require(`./json/ssmcurtis/2016/Geiss - Liquid Beats (janky ripple warp reflecto).json`),
  "martin - disco mix 2": require(`./json/ssmcurtis/2016/martin - disco mix 2.json`),
  "martin - disco mix 4": require(`./json/ssmcurtis/2016/martin - disco mix 4.json`),
  "martin - dont drink and drive (police mix)": require(`./json/ssmcurtis/2016/martin - dont drink and drive (police mix).json`),
  "martin - electric pool": require(`./json/ssmcurtis/2016/martin - electric pool.json`),
  "martin - gate to moria": require(`./json/ssmcurtis/2016/martin - gate to moria.json`),
  "martin - hardcore mix 1": require(`./json/ssmcurtis/2016/martin - hardcore mix 1.json`),
  "martin - hardcore mix 2": require(`./json/ssmcurtis/2016/martin - hardcore mix 2.json`),
  "martin - jellyfish dance": require(`./json/ssmcurtis/2016/martin - jellyfish dance.json`),
  "Martin - liquid arrows": require(`./json/ssmcurtis/2016/Martin - liquid arrows.json`),
  "martin - ludicrous speed": require(`./json/ssmcurtis/2016/martin - ludicrous speed.json`),
  "martin - organic light": require(`./json/ssmcurtis/2016/martin - organic light.json`),
  "martin - silversmith": require(`./json/ssmcurtis/2016/martin - silversmith.json`),
  "martin - tunnel race": require(`./json/ssmcurtis/2016/martin - tunnel race.json`),
  "ORB - Saturns Rings": require(`./json/ssmcurtis/2016/ORB - Saturns Rings.json`),
  "ORB - Supernova Meltdown": require(`./json/ssmcurtis/2016/ORB - Supernova Meltdown.json`),
  "ORB - Waaa": require(`./json/ssmcurtis/2016/ORB - Waaa.json`),
  "phat + Eo.S. - Bass_responce_Red_Movements_Disorienting nebula3": require(`./json/ssmcurtis/2016/phat + Eo.S. - Bass_responce_Red_Movements_Disorienting nebula3.json`),
  "Phat_Eo.S. Eyes_spiral_mix": require(`./json/ssmcurtis/2016/Phat_Eo.S. Eyes_spiral_mix.json`),
  "Phat_Eo.S. rainbow bubble_mid3": require(`./json/ssmcurtis/2016/Phat_Eo.S. rainbow bubble_mid3.json`),
  "Reenen & Telek - Slow Shift Matrix (bb4.5 (Dynamic Beat) Mix)": require(`./json/ssmcurtis/2016/Reenen & Telek - Slow Shift Matrix (bb4.5 (Dynamic Beat) Mix).json`),
  "Reenen - phoenix": require(`./json/ssmcurtis/2016/Reenen - phoenix.json`),
  "Rovastar & Krash - Cerebral Demons (Beat Pulse Mix)": require(`./json/ssmcurtis/2016/Rovastar & Krash - Cerebral Demons (Beat Pulse Mix).json`),
  "Rovastar & Krash - Rainbow Deflection": require(`./json/ssmcurtis/2016/Rovastar & Krash - Rainbow Deflection.json`),
  "Rovastar + Loadus + Geiss - FractalDrop (Spinning Mix)": require(`./json/ssmcurtis/2016/Rovastar + Loadus + Geiss - FractalDrop (Spinning Mix).json`),
  "Rovastar - Cerebral Parasites (Attack Mix)": require(`./json/ssmcurtis/2016/Rovastar - Cerebral Parasites (Attack Mix).json`),
  "Rovastar - Explosive Minds": require(`./json/ssmcurtis/2016/Rovastar - Explosive Minds.json`),
  "Rovastar - Fractopia (Upspoken Mix)": require(`./json/ssmcurtis/2016/Rovastar - Fractopia (Upspoken Mix).json`),
  "Rovastar - Inner Thoughts (Frantic Thoughts Mix)": require(`./json/ssmcurtis/2016/Rovastar - Inner Thoughts (Frantic Thoughts Mix).json`),
  "Rovastar - Solarized Space": require(`./json/ssmcurtis/2016/Rovastar - Solarized Space.json`),
  "Stahlregen & Aderrasi + Flexi + Rovastar - Fractal Twist (A feat. hexcollie)": require(`./json/ssmcurtis/2016/Stahlregen & Aderrasi + Flexi + Rovastar - Fractal Twist (A feat. hexcollie).json`),
  "martin - ghost city": require(`./json/ssmcurtis/2018/Landscapes/martin - ghost city.json`),
  "Rovastar & Loadus - FractalDrop (Active Sparks Mix)": require(`./json/ssmcurtis/2018/Landscapes/Rovastar & Loadus - FractalDrop (Active Sparks Mix).json`),
  "Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash _2": require(`./json/ssmcurtis/2018/Nature/Adam Eatit Mashup FX 2 martin - disco mix + Lodus + Geiss + Raron + Flexi + Moonlight splash _2.json`),
  "cope - ferrofluid [Flexis minor remix]": require(`./json/ssmcurtis/2018/Nature/cope - ferrofluid [Flexis minor remix].json`),
  "cope - the drain to heaven": require(`./json/ssmcurtis/2018/Nature/cope - the drain to heaven.json`),
  "Goody - Need - Desire remix": require(`./json/ssmcurtis/2018/Nature/Goody - Need - Desire remix.json`),
  "qej more i love everything": require(`./json/ssmcurtis/2018/Nature/qej more i love everything.json`),
  "amandio c - spirogen": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spirogen.json`),
  "amandio c - spore -  - eid (-sdi)": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore -  - eid (-sdi).json`),
  "amandio c - spore - dead hogs": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore - dead hogs.json`),
  "amandio c - spore - mess": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore - mess.json`),
  "amandio c - spore - pinecone acorn gujckstamoementomb": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore - pinecone acorn gujckstamoementomb.json`),
  "amandio c - spore - space ferry nz": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore - space ferry nz.json`),
  "amandio c - spore - space ferry": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore - space ferry.json`),
  "amandio c - spore": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - spore.json`),
  "amandio c - stairway to pi": require(`./json/ssmcurtis/2018/Nature/spore/amandio c - stairway to pi.json`),
  "bdrv + al Rovastar - Fractopia (Upspoken Mix)mx 53": require(`./json/ssmcurtis/2018/VintageMovie/bdrv + al Rovastar - Fractopia (Upspoken Mix)mx 53.json`),
  "Eo.S. + Phat - chasers 09 sentinel nz+ cesspratice": require(`./json/ssmcurtis/2018/VintageMovie/Eo.S. + Phat - chasers 09 sentinel nz+ cesspratice.json`),
  "Eo.S. + Phat - chasers 18 hallway": require(`./json/ssmcurtis/2018/VintageMovie/Eo.S. + Phat - chasers 18 hallway.json`),
  "Flexi, martin + geiss - dedicated to the sherwin maxawow": require(`./json/ssmcurtis/2018/VintageMovie/Flexi, martin + geiss - dedicated to the sherwin maxawow.json`),
  "Rovastar - Fractopia (Fantic Dancing Lights Mix)": require(`./json/ssmcurtis/2018/VintageMovie/Rovastar - Fractopia (Fantic Dancing Lights Mix).json`),
};
export default presets;
